### ISSUE TITLE
I can't open teacup!

### ISSUE THREAD

**Issue by dyumanaditya** [goodeggs/teacup-backbone-example#1]
hi,
I'm trying to use teacup with my arduino uno r3, so i followed the instructions on [rep rap [wiki](http://reprap.org/wiki/Teacup_Firmware#Simple_Installation). I installed the teacup master branch package and python 2.7.12. And then they told you to double click on configtool.py. Every time I would do that it wouldn't open. 
Can you please tell me how to do it. Also how to upload it onto my arduino.
If i've understood correctly, teacup is a firmware which needs to be uploaded, and then you need to use a printing software to make your 3d printer work. I'm not too sure about this so please correct me.
Also is there anything else i need to install to make teacup work?
Thanks a lot for your help in advance.

**Comment by dyumanaditya** [comment]
Can someone please reply this is urgent.

**Comment by asalant** [comment]
Hi! This project you are commenting on is for a HTML templating library for CoffeeScript & Node.js. Based on the wiki link you shared, I think you are looking for help with a different Teacup.
